// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MiZVtV9xgwLHvz3huRNKikhgoOSLdiA',
    appId: '1:618412870084:web:6920f8f2ae1110437dbc91',
    messagingSenderId: '618412870084',
    projectId: 'e-commerce-9bb1c',
    authDomain: 'e-commerce-9bb1c.firebaseapp.com',
    storageBucket: 'e-commerce-9bb1c.firebasestorage.app',
    measurementId: 'G-ZTCSX0QGWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMiuTwHXMxWLVC91zwm9VDqw5W0q0ngM',
    appId: '1:618412870084:android:152480847a7f31887dbc91',
    messagingSenderId: '618412870084',
    projectId: 'e-commerce-9bb1c',
    storageBucket: 'e-commerce-9bb1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwkt2GkYDPle6cr-VoZp-t4UAT5Hpixs',
    appId: '1:618412870084:ios:f1d667b8f7f2145a7dbc91',
    messagingSenderId: '618412870084',
    projectId: 'e-commerce-9bb1c',
    storageBucket: 'e-commerce-9bb1c.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );
}
